# python -m pip install elasticsearch
# python -m pip install elasticsearch[async]

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "582Jp9566WqoOWpYIAPrwBkF"

# login in elastic cloud, then click on settings to find cloud_id
CLOUD_ID = "demo:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDViMmNiMjMwNWZmZTQxN2U4NWE4OWI4NjBiMmIwMDJlJDUzNTZmMzNkYWUxMDQzNWI4Y2FhMWNhOGUyMTJiZTkx"

from datetime import datetime
from elasticsearch import Elasticsearch

es = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD),
)

doc = {
    'author': 'kimchy',
    'text': 'Elasticsearch: cool. bonsai cool.',
    'timestamp': datetime.now(),
}
res = es.index(index="test-index", id=1, document=doc)
print(res['result'])

res = es.get(index="test-index", id=1)
print(res['_source'])

es.indices.refresh(index="test-index")

res = es.search(index="test-index", body={"query": {"match_all": {}}})
print("Got %d Hits:" % res['hits']['total']['value'])
for hit in res['hits']['hits']:
    print("%(timestamp)s %(author)s: %(text)s" % hit["_source"])